spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/chinese_poetry?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: mengyao-poerty

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # Mapper XML 文件路径
  type-aliases-package: com.wechatapp.mengyao.poetry.entity  # 实体类包别名
  configuration:
    map-underscore-to-camel-case: true  # 自动转换下划线到驼峰命名

logging:
  level:
    root: INFO               # 全局日志级别
    com.wechatapp.mengyao: DEBUG  # 指定包路径的日志级别
  file:
    name: logs/app.log       # 日志输出到文件（默认生成在项目根目录）
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"  # 控制台格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"      # 文件格式

pagehelper:
  helper-dialect: mysql       # 明确指定数据库类型
  reasonable: true            # 分页合理化（pageNum<=0 时返回第一页）
  support-methods-arguments: true
  params: count=countSql      # 确保参数正确传递